Missing unit tests for SlaveWAMPSocketServer - Closes #2
LiskHQ/wamp-socket-cluster pull request #14
Opened 2017-08-08 09:09 UTC by MaciejBaj

Adds missing SlaveWAMPServer tests, jsdocs. This PR fixes also the example.

2017-08-08 10:20 UTC, willclarktech requested changes

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @returns {{}}
Does this mean `object`? Prefer consistency if so. Should `WAMPRequestSchema` or some other specific request type make an appearance here?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @param {Function} cb
`@returns`?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @returns {*}
Not super familiar with this stuff, but is there a better way to specify it returns `undefined`?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @param {Function} cb
`@returns`?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @param {InterProcessRPCRequestSchema} request
`@returns`?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +		return get(this.interProcessRPC, `${request.socketId}.${request.procedure}.${request.signature}`, false);
Prefer passing an array instead of a string.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @param {object} request
Since we set a default argument is there a way to specify this is optional?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
>  		return setWith(this.interProcessRPC, `${request.socketId}.${request.procedure}.${request.signature}`, cb, Object);
Prefer passing an array instead of a string.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
>  		return setWith(this.interProcessRPC, `${request.socketId}.${request.procedure}.${request.signature}`, cb, Object);
Why is `setWith` necessary rather than `set`?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @param {InterProcessRPCResponseSchema} request
`@returns`?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +before(() => {
Prefer placing these within a `describe` block.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +		workerMock.sendToMaster.reset();
These spies were just created so shouldn't need to be reset here.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			const slaveWAMPServer = new SlaveWAMPServer(workerMock);
These can all be removed now you have `slaveWampServer` in the outer scope.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(workerMock.on.calledOnce).to.be.ok();
Prefer `.to.be.true()` for known booleans.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(workerMock.on.calledWith('masterMessage')).to.be.ok();
Prefer `calledWithExactly`.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +		let normalizeRequest;
This should be safe to store in a `const`: the static method isn't mutating, right?!

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			socketMock.send.reset();
Resets can be removed.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +		let validProcedure;
`const` is fine here as strings are immutable.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +		let validSocketId;
As above.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			validSignature = `${new Date().getTime()}_0`;
Does this need to be different for each test? If not `const` is fine as it's just another string.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			sinon.stub(Math, 'random').returns(0);
Restore?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				type: '/InterProcessRPCRequestSchema',
Prefer defining all variables together.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +		const actionCb = sinon.spy();
Doesn't look like you're using this spy.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(slaveWampServer.interProcessRPC[validSocketId][validProcedure]).to.have.property(validSignature).to.be.a('function');
These can be combined into a single `expect` statement.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			validSignature = 'validSignature';
Strings can be `const`s.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			validCb = () => {};
This can probably go in a `const` since it's not a spy, assuming we won't be mutating callback functions.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			validSignature = 'validSignature';
Strings can be `const`.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			}).to.throw('Cannot save a call for wrong InterProcessRPCRequest request');
`expect(slaveWampServer.saveCall).to.throw('...');`

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				slaveWampServer.saveCall(validRequest, validCb);
Personally prefer
```
expect(slaveWampServer.saveCall.bind(slaveWampServer, validRequest, validCb)).to.throw('...');
```
but I appreciate views differ here.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(slaveWampServer.interProcessRPC[validSocketId][validProcedure]).to.have.property(validSignature).to.be.a('function');
Combine `expect` statements.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			const validRequestB = validRequest;
Prefer creating a new object.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				.to.have.property(validRequestB.signature).to.be.a('function');
Combine `expect` statements.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			validSignature = 'validSignature';
Strings can be `const`.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				slaveWampServer.deleteCall();
`expect(slaveWampServer.deleteCall).to.throw`

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			}).to.throw('There is no internal requests registered for socket: validSocketId, procedure: validProcedure with signature validSignature');
No `empty` expectation here?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			validSignature = 'validSignature';
These same strings are reused in lots of different blocks - it would be neater to define them (as `const`) in an outer block.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				};
This is also reused in different blocks - maybe put it in a helper function?

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			it('should return false when invoked without signature', () => {
Duplicate test.

2017-08-08 10:20 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +after(() => {
Prefer placing this near `before`.

2017-08-08 10:20 UTC, willclarktech commented on WAMPClient.spec.js
> +			});
This should be done in an `after` hook in the the other file.

2017-08-08 10:20 UTC, willclarktech commented on WAMPClient.spec.js
> +				after(() => {
Prefer placing this near the `before` hook.

2017-08-08 10:31 UTC, MaciejBaj commented on WAMPClient.spec.js
> +			});
ok, thanks

2017-08-08 10:31 UTC, MaciejBaj commented on WAMPClient.spec.js
> +				after(() => {
ok, thanks

2017-08-08 10:32 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
> +			it('should return false when invoked without signature', () => {
thanks

2017-08-08 10:34 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
> +				slaveWampServer.deleteCall();
thanks

2017-08-08 10:48 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @param {object} request
yes, ofc

2017-08-08 10:49 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @param {Function} cb
the function itself is void as it returns a value through a callback

2017-08-08 10:57 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @returns {*}
actually the function is void, so i will just remove `returns` statament

2017-08-08 10:58 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @param {Function} cb
So `@returns {undefined}`? Best to be explicit.

2017-08-08 10:59 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @returns {{}}
right, i will change `@param {object}` also to `@param {Object}` to be constistent with lisk-core https://github.com/LiskHQ/lisk/issues/691

2017-08-08 11:03 UTC, MaciejBaj commented
@willclarktech regarding using `const` instead of `let`. Generally, I agree with, but it makes a lot of sense to me to use `let` in tests and reset them before every test. It introduces easiness of modifying variables in tests without creating extra variables to avoid mutating originals.

2017-08-08 13:06 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
> +			expect(workerMock.on.calledWith('masterMessage')).to.be.ok();
in this case it is called with some other params (callback) as well

2017-08-08 13:09 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
> +			const validRequestB = validRequest;
it is initialized in `beforeEach` section anyway

2017-08-08 13:11 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			const validRequestB = validRequest;
Well why create a new `const` then?

2017-08-08 13:22 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @param {Function} cb
ok

2017-08-09 01:09 UTC, jondubois commented on SlaveWAMPServer.js
> +		return setWith(this.interProcessRPC, `${request.socketId}.${request.procedure}.${request.signature}`, cb, Object);
From what I understood, here you use a unique signature to keep track of a response callback for a specific user RPC; then you pass the request to the master process; then the master process executes the procedure and then sends back the result to the slave server; then the slave looks up the response callback using the signature and passes the result of the procedure back to the client/user.

One case to consider is what would happen if the master process doesn't respond... Like if there is a bug in the procedure's logic on the master process which makes it not return properly (e.g. the procedure never invokes its `cb(...)`). Do you have some sort of timeout error to deal with this? Like a maximum time limit for how long an RPC can take? The potential concern is that if a response doesn't come back from the master process, then it won't be removed from `this.interProcessRPC` and they might just pile up over time (at least until the socket disconnects).

2017-08-09 08:27 UTC, willclarktech requested changes

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.called).to.be.ok();
Prefer `.to.be.true()` for booleans. Does it take any arguments? If so prefer specifying what it was called with. If not maybe consider `.calledWithExactly()`?

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.calledWith(validMasterWAMPRequest)).to.be.ok();
Prefer `calledWithExactly`.

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					sinon.stub(masterWAMPServer, 'reply');
This could also be put into a `stub` variable so it's clear later on that it's the same stub in each case.

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.reply.calledWith(null)).to.be.ok();
`calledWithExactly`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					}).to.be.ok();
`expect(...).to.eql(...);`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					sinon.stub(masterWAMPServer, 'reply');
`stub` variable

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +				it('should not modify empty workerIndices map', () => {
`workerIndices array`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +			expect(masterWAMPServer.socketCluster.sendToWorker.args[0][1]).eql({
`.to.eql`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +			expect(masterWAMPServer.socketCluster.sendToWorker.calledWith(validWorkerId)).to.be.ok();
`calledWithExactly`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +		it('should invoke socketCluster.sendToWorker with a valid error WAMPResponse in case of passing error message', () => {
Remove " in case of passing error message"

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +			expect(masterWAMPServer.socketCluster.sendToWorker.calledWith(validWorkerId)).to.be.ok();
`calledWithExactly`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +			expect(masterWAMPServer.socketCluster.sendToWorker.args[0][1]).eql({
`.to.eql`

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					validKey: 'validValue',
Prefer storing these in constants to avoid magic strings.

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +				type: '/WAMPResponse',
Magic string.

2017-08-09 08:27 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +				error: 'Custom error',
Magic strings.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @returns {undefined}
?

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @returns {undefined}
Shouldn't do.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @returns {InterProcessRPCRequestSchema|false}
It returns a signature, right?

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +		return get(this.interProcessRPC, `${request.socketId}.${request.procedure}.${request.signature}`, false);
Prefer an array for the path.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +			throw new Error(`There is no internal requests registered for socket: ${request.socketId}, procedure: ${request.procedure} with signature ${request.signature}`);
`There are`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +			throw new Error('Cannot delete a call for wrong InterProcessRPCRequest request');
Can we make this error more helpful?

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.js
> +	deleteCall(request = {}) {
Consider destructuring `socketId`, `procedure`, and `signature` out immediately here for ease of reading in the function body.

2017-08-09 08:27 UTC, willclarktech commented on WAMPServer.spec.js
>  			expect(socket.on.calledWith('raw')).to.be.ok();
Prefer `calledWithExactly`, `.to.be.true`.

2017-08-09 08:27 UTC, willclarktech commented on WAMPServer.spec.js
>  			expect(endpoint.procedureA.calledWith('valueA')).to.be.ok();
As above.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +});
Prefer setting these hooks within a `describe` block.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +	const validSocketId = 'validSocketId';
👌

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(workerMock.on.calledWith('masterMessage')).to.be.ok();
Prefer `calledWithExactly` and `.to.be.true`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			expect(workerMock.sendToMaster.calledWith(validSlaveToMasterRequest)).to.be.ok();
`calledWithExactly`, `.true`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				workerId: 0,
Magic strings/numbers.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			expect(endpoint.procedureName.calledWith({
`Exactly`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			expect(workerMock.sendToMaster.called).not.to.be.ok();
`.to.be.false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				workerId: 0,
Magic

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			})).to.be.ok();
`true`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			})).to.be.ok();
`true`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			expect(endpoint.procedureName.calledWith({
`Exactly`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			})).to.be.ok();
`true`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
>  			expect(workerMock.sendToMaster.called).not.to.be.ok();
`false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(workerMock.sendToMaster.calledWith({
`Exactly`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			})).to.be.ok();
`true`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			}).to.throw('Cannot save a call for wrong InterProcessRPCRequest request');
These error messages could be stored somewhere.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			const validRequestB = validRequest;
If you're happy to mutate the object, just use `validRequest`. If you want `validRequestB` to be a different object, create a new one.

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(slaveWAMPServer.getCall()).to.be.not.ok();
`false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			expect(slaveWAMPServer.getCall(validRequest)).to.be.not.ok();
`false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				expect(slaveWAMPServer.getCall()).to.be.not.ok();
`false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				expect(slaveWAMPServer.getCall()).to.be.not.ok();
`false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				expect(slaveWAMPServer.getCall()).to.be.not.ok();
`false`

2017-08-09 08:27 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +				expect(slaveWAMPServer.getCall(validRequest)).to.be.ok();
`true`

2017-08-09 09:40 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +		return setWith(this.interProcessRPC, `${request.socketId}.${request.procedure}.${request.signature}`, cb, Object);
Very valid point, thank you. You are right, callbacks will stack and will never be resolved. I will open a separate issue to address it.

2017-08-09 10:53 UTC, MaciejBaj commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.called).to.be.ok();
checked in the next test

2017-08-09 10:54 UTC, MaciejBaj commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.calledWith(validMasterWAMPRequest)).to.be.ok();
not true in this case

2017-08-09 10:55 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.called).to.be.ok();
Or `calledOnce`?

2017-08-09 10:56 UTC, MaciejBaj commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.reply.calledWith(null)).to.be.ok();
function accepts 4 args

2017-08-09 10:57 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.calledWith(validMasterWAMPRequest)).to.be.ok();
<img width="451" alt="screen shot 2017-08-09 at 12 56 44" src="https://user-images.githubusercontent.com/11036220/29118436-3fc4d3b0-7d02-11e7-8972-015dd28de808.png">

2017-08-09 10:57 UTC, MaciejBaj commented on MasterWAMPServer.spec.js
> +			expect(masterWAMPServer.socketCluster.sendToWorker.calledWith(validWorkerId)).to.be.ok();
function accepts 2 args

2017-08-09 10:58 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.processWAMPRequest.calledWith(validMasterWAMPRequest)).to.be.ok();
The 'exactly' here refers to the arguments, not object identity.

2017-08-09 10:59 UTC, willclarktech commented on MasterWAMPServer.spec.js
> +					expect(masterWAMPServer.reply.calledWith(null)).to.be.ok();
Ah, then can you specify which position `null` should appear?

2017-08-09 11:02 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @returns {undefined}
lodash setWith is a void function

2017-08-09 11:04 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @returns {InterProcessRPCRequestSchema|false}
actually it returns a function

2017-08-09 11:43 UTC, willclarktech commented on SlaveWAMPServer.js
> +	 * @returns {undefined}
https://lodash.com/docs/4.17.4#setWith says it returns the object.

2017-08-09 11:56 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	 * @returns {undefined}
fair enough

2017-08-09 11:56 UTC, MaciejBaj commented on SlaveWAMPServer.js
> +	deleteCall(request = {}) {
I will leave the current construction as it will make simpler to pass the params between reset /  get / save calls

2017-08-09 11:58 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
> +			}).to.throw('Cannot save a call for wrong InterProcessRPCRequest request');
it will complicate the current structure, I don't like the idea

2017-08-09 14:00 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
>  			expect(endpoint.procedureName.calledWith({
wouldn't work here

2017-08-09 14:00 UTC, MaciejBaj commented on SlaveWAMPServer.spec.js
>  			expect(endpoint.procedureName.calledWith({
wouldn't work here

2017-08-09 14:35 UTC, willclarktech commented on SlaveWAMPServer.spec.js
> +			}).to.throw('Cannot save a call for wrong InterProcessRPCRequest request');
It's difficult to see the relationship between these errors without storing it in a common variable.

2017-08-10 13:11 UTC, willclarktech approved these changes

2017-08-10 13:16 UTC, merged