Handle case of signature generation failure - Closes #15
LiskHQ/wamp-socket-cluster pull request #17
Opened 2017-08-10 14:36 UTC by MaciejBaj

- control attempts of signature generations through `MAX_GENERATE_ATTEMPTS` 
- return failure error message to the client when generating the signature fails
closes #15

2017-08-10 15:15 UTC, Isabello commented on WAMPClient.js
> +		return 100000;
This seems incredibly high. Is there a reason to set the constant to 100k?

2017-08-10 15:27 UTC, Isabello requested changes
<3

2017-08-10 15:27 UTC, Isabello commented on WAMPClient.spec.js
> +		it('should generate a signature when empty procedureCalls given', () => {
should generate a signature when empty procedureCalls are passed

2017-08-10 15:27 UTC, Isabello commented on WAMPClient.spec.js
> +		it('should generate a signature in a proper format', () => {
should generate a signature matching expected format

2017-08-10 15:27 UTC, Isabello commented on WAMPClient.spec.js
>  			it('should create 2 correct entries for calling twice the same procedures', () => {
should create 2 correct entries for calling the same procedure

2017-08-10 15:27 UTC, Isabello commented on WAMPClient.spec.js
> +				it('should throw an error when invalid request signature provided', (done) => {
should throw an error when provided an invalid request signature

2017-08-10 15:29 UTC, MaciejBaj commented on WAMPClient.js
> +		return 100000;
tests are ok with that, suspending max for 1 sec

2017-08-10 15:34 UTC, MaciejBaj commented on WAMPClient.js
> +		return 100000;
actuaactually not fine for Jenkins - timeouts. I will decrease it x10

2017-08-14 07:56 UTC, Isabello approved these changes

2017-08-14 07:56 UTC, merged